# Generated by Django 4.0.1 on 2022-02-08 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=20)),
                ('course_subtitle', models.CharField(max_length=250)),
                ('course_description', models.TextField(max_length=250)),
                ('course_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('EXPERT', 'EXPERT')], max_length=100)),
                ('course_category', models.CharField(choices=[('IT', 'IT'), ('BUSINESS', 'BUSINESS'), ('SPORT', 'SPORT')], max_length=100)),
                ('course_image', models.ImageField(default='profile.png', upload_to='images/')),
                ('duration', models.IntegerField()),
                ('course_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.register_course')),
            ],
        ),
    ]
